Version: 0.0
GoogleIME:
  Enable: true
GoogleTranslate:
  Enable: true
  ScriptURL: ''
  LanguageCodes:
    - 'JA'
    - 'EN'
    - 'ZH'
ChannelChat:
  Enable: true
Mail:
  Enable: true
  ExpirationDays: 30
  Processors: []
  Format:
    Normal: '[player]&a:&r [message]'
    Japanized: '[player]&a:&r [japanized]&7([message])'
    Translation: '[player]&a:&r [translation]&7([message])'