Version: 0.0
ForceJoinChat: []
NGWordMask:
  Enable:
  NGWords:
  - 'uruse'
PlaceHolder:
  Enable:
  Holders:
  - 'あまちゃっと[:]Amachat'
GoogleIME:
  Enable: true
GoogleTranslate:
  Enable: true
  ScriptURL: ''
  LanguageCodes:
    - 'JA'
    - 'EN'
    - 'ZH'
ChannelChat:
  Enable: true
Privatechat:
  Enable: true
  Format: '[&a[chat]]&r[player]&a>&r [message]'
  MessageFormats:
    Normal: '[converted]'
    Japanize: '[converted]&7([original])'
    Translate: '[converted]&7([original])'
Mail:
  Enable: true
  ExpirationDays: 30
  Processors: []
  Format: '[&a[chat]]&r[player]&a>&r [message]'
  MessageFormats:
    Normal: '[converted]'
    Japanize: '[converted]&7([original])'
    Translate: '[converted]&7([original])'